# Chapter 3: Vector Multiplications

In [1]:
# standard libraries to import
import numpy as np
import matplotlib.pyplot as plt

There are 4 ways to multiply a pair of vectors:
1. Dot product
2. Outer product
3. Element-wise multiplication
4. Cross product

The Dot product is most important and covered the most in this chapter

## 3.1 Dot Product

- Dot products are 2 matrices multiplied element-wise, then sum all individual products.
  - *note: Some textbooks use an actual dot symbol, but this book specifically uses the superscript ^T for dot product.*
- requires 2 vectors of equal dimensionality (otherwise it's undefined)
- The result of the dot product is always a scalar (1 number) and not a matrix.
- The dot product of a vector with itself is its magnitude squared.
- The vector dot product **does not** obey the **associative** property (you can't arbitrarily subdivide with parentheses).
  - *note that confusingly, matrix multiplication (covered later) **does** obey the associative property*.
- The dot product **is** **commutative** (you can switch the order of terms) e.g.: $$a^Tb = b^Ta$$
- The dot product **is** **distributive** (scalars distribute inside parentheses) e.g.: $$w^T(u+v) = w^Tu + w^Tv$$

In [2]:
# Dot product code example:
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])
dp = np.dot(v1, v1)
print(dp)

94


*Note: 3Blue1Brown has an excellent video on the Dot Product (and Linear Algebra intuition in general)*

[3Blue1Brown - Dot product](https://www.youtube.com/watch?v=LyGKycYT2v0&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=9)

[3Blue1Brown - Essence of Linear Algebra (All 16 videos)](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

### Cauchy-Schwarz inequality
$$|v^Tw| <= \|v\|*\|w\|$$

- provides an upper bound for the dot product between 2 vectors
- in English, this inequality says that the magnitude (absolute value) of the dot product between two vectors is no larger than the product of the norms of the individual vectors.  The expressions will equal each other when one vector is a scaled version of the other vector, that is, when $$v = \lambda*w$$

## 3.3 Vector Dot Product Geometry

Geometrically, the dot product is the cosine of the angle between the two vectors, times the lengths (magnitudes) of the two vectors.

$$a^Tb = \|a\| \|b\| \cos(\theta_{ab})$$
*note that if both vectors have unit length (magnitude = 1) then the equation reduces to the cosine of the angle between the 2 vectors.*

This formula can be rearranged in order to solve for the angle between 2 vectors

**Pearson correlation coefficient:** (more on this in ch 18)
$$\cos(\theta_{ab}) = \frac{a^Tb}{\|a\| \|b\|}$$

**Solved for angle:**
$$\theta_{ab} = \cos^-1 \frac{a^Tb}{\|a\| \|b\|}$$

The sign (+/-) of the dot product between 2 vectors is determined entirely by the angle between the 2 vectors.  This is a powerful relationship and provides a geometric intuition for every application of the dot product (which are many).

This is because lengths (magnitudes) are always a positive value, while cosine can range from -1 to 1.

### Dot Product Categories
We can group dot products into 5 categories based on the angle:

**1. Acute**  
The cosine of an acute angle is always positive, so the dot product will be positive.
$$\theta < 90^\circ \rightarrow \alpha > 0$$

**2. Obtuse**  
The cosine of an obtuse angle is always negative, so the dot product will be negative.
$$\theta > 90^\circ \rightarrow \alpha < 0$$

**3. Right angle / orthogonal**  
The cosine of a right angle is 0, so the dot product will always be 0, regardless of the magnitudes.  
This is sucn an important case that it has its own name **orthogonal**.
$$\theta = 90^\circ \rightarrow \alpha = 0$$

**4. Collinear (same direction)**  
The cosine of 0 is 1, so the dot product reduces to the product of the magnitudes.  
The term for this situation is **collinear** (meaning on the same line).
$$\theta = 0^\circ \rightarrow \alpha = \|a\| \|b\|$$

**5. Collinear (opposite direction)**  
Basically the same as #4 above, but with a negative sign because cos(180) = -1.  
This is also **collinear** but note that the 2 vectors will point in opposite directions.
$$\theta = 180^\circ \rightarrow \alpha = -\|a\| \|b\|$$

<img src="img/03/dot-product-categories.jpeg" alt="Dot Product Categories" width=700>

## 3.4 Algebraic and geometric equivalence

The algebraic and geometric versions of the dot product look very different and its not intuitive at first why they're the same.

<img src="img/03/dot-equivalence.jpeg" alt="Dot product algebraic and geometric equivalence" width=600>

Proving equivalence requires the Law of Cosines

(reminder: Law of cosines is a generalized version of Pythagorean theorem that works for all triangles not just right triangles)

<img src="img/03/law-of-cos-1.jpeg" alt="Law of cos 1" width="200"/>
<img src="img/03/law-of-cos-2.jpeg" alt="Law of cos 2" width="600"/>

## 3.5 Linear Weighted Combination

In [3]:
import numpy as np
l1 = 1
l2 = 2
l3 = -3
v1 = np.array([4,5,1])
v2 = np.array([-4,0,-4])
v3 = np.array([1,3,2])
l1*v1 + l2*v2 + l3*v3

array([ -7,  -4, -13])

## 3.6 The outer product

In [4]:
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])
op = np.outer(v1, v2)
print(op)

[[ 8  2  0  4]
 [20  5  0 10]
 [16  4  0  8]
 [28  7  0 14]]


## 3.7 Element-wise (Hadamard) vector product

In [5]:
v1 = np.array([2,5,4,7])
v2 = np.array([4,1,0,2])
v3 = v1 * v2
print(v3)

[ 8  5  0 14]


## 3.8 Cross Product

## 3.9 Unit vectors

In [6]:
v = np.array([2,5,4,7])
vMag = np.linalg.norm(v)
v_unit = v / vMag
print(v_unit)

[0.20628425 0.51571062 0.4125685  0.72199487]


## 3.10 - 3.11 Practice Problems

## 3.12 Code Challenges

1. Create a linear weighted combination of 3 vectors.

Create 3 5-D vectors and a 4th vector that contains the weights for each vector.  Then create the weighted sum of those vectors.  Next, modify the code to compute the weighted mixture of 4 5-D vectors.  What's the relationship between the dimensionality of the to-be-summed vectors, the number of vectors to sum, and the dimensionality of the coefficients vector?

In [7]:
v1 = np.array([4,5,1,7,6])
v2 = np.array([-4,0,-4,3,-7])
v3 = np.array([1,3,2,5,4])
w = np.array([1,2,3,])
weighted_sum = v1*w[0] + v2*w[1] + v3*w[2]
print(weighted_sum)

[-1 14 -1 28  4]


In [8]:
v1 = np.array([4,5,1,7,6])
v2 = np.array([-4,0,-4,3,-7])
v3 = np.array([1,3,2,5,4])
v4 = np.array([7,4,1,-8,3])
w = np.array([1,2,3,4])
weighted_sum = v1*w[0] + v2*w[1] + v3*w[2] + v4*w[3]
print(weighted_sum)

[27 30  3 -4 16]


dive into relationship question later with group

2.  Develop a method to use the dot product to compute the average set of numbers in a vector. (Hint: consider the vector of all ones, sometimes written **1**.)

In [9]:
v = [9,6,2,-3,8,13,5,1]
ones = np.ones(len(v))
avg = np.dot(v,ones) / len(v)
print(avg)

5.125


3. What if some numbers were more important than other numbers?  Modify your answer to the previous question to devise a method to use the dot product to compute a weighted mean of a set of numbers.

In [18]:
v = np.array([9, 6, 2, -3, 8, 13, 5, 1])
w = np.array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8])  # arbitrary weight values
weighted_avg = np.dot(v, w / sum(w))
print(weighted_avg)

4.888888888888889
