# Chapter 5: Matrices

In [1]:
# standard python libraries to import
import numpy as np
import matplotlib.pyplot as plt

## 5.1 Interpretations and uses of matrices

- This book focuses on matrices that you can "lay down on a table", though they are not necessarily 2D matrices, as each row/column of a matrix is a dimension.
- Matrices that don't lay flat on a table are *tensors* (e.g. tensor calculus used in GR)
- Tensors will not be discussed in this book.

Matrices are ubiquitous and have innumerable uses.  A few examples:
- representing a linear transformation or mapping
- storing partial derivatives of a multivariable system
- representing a system of equations
- storing data (e.g. features x observations)
- representing regressors for statistical modeling
- storing geometric transformations for computer graphics
- storing kernels used in filtering or convolution
- representing finance information from various sectors of an economy or business
- housing parameters for a model that predicts changes in the spread of an infectious disease

## 5.2 Matrix terminology and notation

- mostly review...skipping the basics
- A "block matrix" is a matrix that comprises smaller matrices (note: this book doesn't cover block matrices)
- Matrix notation is typically M rows by N columns (mnemonic "**M**(R). **N**i(C)e guy")

## 5.3 Matrix dimensionalities

- Matrices are flexible with their notation, and flexibility can lead to confusion
- In practice, the dimensionality of a given matrix is made on a case-by-case basis, and is either explicitly stated, or is inferred from context.

## 5.4 The transpose operation

- transposing a matrix is the same as transposing a vector: swap rows and columns
  - $B_{i,j} = A_{j,i}$
- transposing a matrix twice gives you the original matrix
  - $A^{TT} = A$
- example of a transposed matrix:
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}^T = 
\begin{bmatrix}
1 & 4 \\
2 & 5 \\
3 & 6
\end{bmatrix}

*note that transposing is like drawing a diagonal line and flipping the matrix*

*first always stays first (i.e. 1st row -> 1st column, or 1st column -> 1st row)*

#### Code

In [2]:
# Transposing in code is the same as transposing vectors
A = np.random.randn(2,5)
print(A)

[[-1.41161668 -1.21611103  0.47007338  0.5131717   0.54573685]
 [-0.9451269  -0.9422239   0.77957286  1.11176834 -0.79065985]]


In [3]:
# option 1) using numpy's .T method
At1 = A.T
print(At1)

[[-1.41161668 -0.9451269 ]
 [-1.21611103 -0.9422239 ]
 [ 0.47007338  0.77957286]
 [ 0.5131717   1.11176834]
 [ 0.54573685 -0.79065985]]


In [4]:
# option 2) using numpy's .transpose method
At2 = np.transpose(A)
print(At2)

[[-1.41161668 -0.9451269 ]
 [-1.21611103 -0.9422239 ]
 [ 0.47007338  0.77957286]
 [ 0.5131717   1.11176834]
 [ 0.54573685 -0.79065985]]


## 5.5 Matrix zoology

- "fat" / wide matrices have more columns than rows
- "skinny" / tall matrices have more rows than columns

### Symmetric matrices

- a matrix is symmetric if it's mirrored across the diagonal
- A matrix is symmetric if it equals its transpose
- only square matrices can be symmetric (obviously)
- $A = A^T$
- $a_{i,j} = a_{j,i}$

\begin{bmatrix}
1 & 4 & \pi \\
4 & 7 & 2 \\
\pi & 2 & 0
\end{bmatrix}

- Symmetric matrices have many special properties and will be used throughout this book
- There are 2 ways to convert non-symmetric matrices into symetric matrices. Both will be covered in future chapters.

### Skew-symmetric

- skew symmetric matrices are where the lower triangle is the sign flipped version of the upper triangle
- The diagonal on a skew symmetric matrix must be 0 (positive and negative combined)
- $A = -A^T$
- $a_{i,j} = -a_{j,i}$


\begin{bmatrix}
0 & -4 & 8 \\
4 & 0 & -5 \\
-8 & 5 & 0
\end{bmatrix}

*note: I believe Hermitian matrices from physics are a type of skew-symmetric matrices in the Complex space*

### Identity

- The identity matrix $I$ is equal to the number 1 (anything multiplied by it = itself)
- 1's in diagonal, 0's everywhere else
- always a square matrix

\begin{bmatrix}
1 & 0 & ... & 0 \\
0 & 1 & ... & 0 \\
... & ... & ... & ... \\
0 & 0 & ... & 1
\end{bmatrix}

### Zeros

- obviously just a matrix of 0's
- can be either square or rectangular
- also called the *additive identity matrix* (since adding zero to anything gives you the original)

#### Code

In [5]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
O = np.ones(4)
print(O)

[1. 1. 1. 1.]


In [7]:
Z = np.zeros((4,4))
print(Z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### $A^TA$

- $A^TA$ is sometimes written as `AtA`
- $A^TA$ is one of the most important forms in all of applied linear algebra (covered in more detail next chapter)
- $AA^T$ is identical to $A^TA$, but $A^TA$ notation is used far more often

Important properties of $A^TA$:
- always a square matrix, even if A is rectangular
- Symmetric, even if A isn't
- it is full-rank if A is full column-rank
- it is invertible if A is full column-rank
- it has the same row space as A
- it has orthogonal eigenvectors
- it is positive (semi)definite.
- it has non-negative, real-valued eigenvalues.
- it is called a "covariance matrix" if A is a data matrix.
- if often looks pretty

### Diagonal

- only has values in the diagonal direction, everything else is zeroes
- diagonal can also be rectangular
- $I$ is one example of a diagonal, as is the following

\begin{bmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3
\end{bmatrix}, 
\begin{bmatrix}
7 & 0 & 0 & 0 \\
0 & \pi & 0 & 0
\end{bmatrix}

- If all the diagonal values are the same, then it can be written as a constant * Identity matrix

$\begin{bmatrix}
7 & 0 \\
0 & 7
\end{bmatrix} = 
7\begin{bmatrix}
1 & 0 \\
0 & 1
\end{bmatrix}
= 7I_2$

- Diagonal matrices are useful because they simplify operations like matrix multiplication and exponentiation.
- transforming a matrix into a diagonal is called *diagonalization* (covered later)
- $D$ is often used to indicate diagonal matrix, but note that there are many diagonal matrices not labeled $D$

#### Hollow Matrix

- The opposite of a diagonal matrix is a hollow matrix (0's on the diagonal)
- skew symmetric matrices are hollow

#### Code

In [8]:
D = np.diag([1,2,3,5])  # diagonal matrix
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 5]]


In [9]:
R = np.random.randn(3,4)
print(R)

[[ 1.25607797  1.72881214  1.21727037  1.10899124]
 [ 1.55298419 -1.04585951  0.33354721 -0.42996085]
 [ 0.3629378   0.54006763 -1.13988925 -0.18631023]]


In [10]:
d = np.diag(R)  # diagonal elements
print(d)

[ 1.25607797 -1.04585951 -1.13988925]


### Augmented

- Augmented matrix is the result of concatenating two or more matrices column-wise
  - i.e. tacking the columns from one matrix on the end of another
- You can only augment 2 matrices if they have the same number of rows (# of columns doesn't matter)

#### Code

In [11]:
# Augmenting matrix A and B => AB
A = np.random.randn(3,4)
print(A)

[[-1.26249398 -0.67722691  0.87703506  0.67116257]
 [ 1.0658431   1.15603787 -0.76561395 -1.89663767]
 [-0.18867572  0.90908705  0.46733587 -0.97567469]]


In [12]:
B = np.random.randn(3, 2)
print(B)

[[ 0.47895943 -1.87411373]
 [ 0.04352454  0.62603456]
 [ 0.60871343 -0.41021281]]


In [13]:
AB = np.concatenate((A,B), axis=1)
print(AB)

[[-1.26249398 -0.67722691  0.87703506  0.67116257  0.47895943 -1.87411373]
 [ 1.0658431   1.15603787 -0.76561395 -1.89663767  0.04352454  0.62603456]
 [-0.18867572  0.90908705  0.46733587 -0.97567469  0.60871343 -0.41021281]]


### Triangular

- only 1/2 the matrix has non-zero numbers (including diagonal)
- two kinds: upper triangle, lower triangle
- can be rectangular
- sometimes, the zeros are left off / ignored for visual clarity

#### Code

In [14]:
# Triangle matrices (lower and upper)
A = np.random.randn(4,5)
print(A)

[[-0.62591698 -0.04456701 -1.98938648 -0.27177842  1.55744001]
 [-0.11776518  1.06501241 -0.62304516 -0.76340111  1.26249623]
 [-0.52582349 -1.12118143 -0.42498259 -1.45269199  1.12817169]
 [-1.1159101   0.60457932  0.56897016 -1.34366123 -0.08035565]]


In [15]:
L = np.tril(A)  # tril(ower) extracts the lower triangle
print(L)

[[-0.62591698  0.          0.          0.          0.        ]
 [-0.11776518  1.06501241  0.          0.          0.        ]
 [-0.52582349 -1.12118143 -0.42498259  0.          0.        ]
 [-1.1159101   0.60457932  0.56897016 -1.34366123  0.        ]]


In [16]:
U = np.triu(A)  # triu(pper) extracts the upper triangle
print(U)

[[-0.62591698 -0.04456701 -1.98938648 -0.27177842  1.55744001]
 [ 0.          1.06501241 -0.62304516 -0.76340111  1.26249623]
 [ 0.          0.         -0.42498259 -1.45269199  1.12817169]
 [ 0.          0.          0.         -1.34366123 -0.08035565]]


### Dense and sparse

- a matrix in which most or all of the elements are non-zero is called a **dense** matrix (sometimes also called a full matrix)
- dense/full is usually used in comparison to another matrix
- a **sparse** matrix contains mostly zeros and a relatively small number of non-zero elements
- sparse elements are very computationally efficient which is why many modern algorithms utilize them

### Orthogonal

- orthogonal matrices satisfy the following:
  - all columns are pairwise orthogonal.  This means that the dot product between any 2 columns is exactly 0.
  - Each column *i* has unit magnitude: $\|Q_i\|=1$.
    - *(remember that the magnitude of a vector/column of a matrix is the dot product of the vector with itself)*

- $Q$ is often used to indicate orthogonal matrix (but not always)
- $Q^TQ = I$

### Toeplitz

- Toeplitz and Hankel matrices are closely related.
- In a Toeplitz matrix, all diagonals contain the same element

A Toeplitz matrix created from a vector:

$$
\begin{bmatrix}
a & b & c & d
\end{bmatrix} =>
\begin{bmatrix}
a & b & c & d \\
d & a & b & c \\
c & d & a & b \\
b & c & d & a
\end{bmatrix}
$$

### Hankel

- the opposite of a Toeplitz matrix (anti-diagonal)

A Hankel matrix created from a vector:

$$
\begin{bmatrix}
a & b & c & d
\end{bmatrix} =>
\begin{bmatrix}
a & b & c & d \\
b & c & d & 0 \\
c & d & 0 & 0 \\
d & 0 & 0 & 0
\end{bmatrix}
$$
or with wrap-around:
$$
\begin{bmatrix}
a & b & c & d \\
b & c & d & a \\
c & d & a & b \\
d & a & b & c
\end{bmatrix}
$$

#### Code

In [17]:
# Toeplitz matrix
from scipy.linalg import hankel, toeplitz
t = [1,2,3,4]
T = toeplitz(t)
print(T)

[[1 2 3 4]
 [2 1 2 3]
 [3 2 1 2]
 [4 3 2 1]]


In [18]:
# Hankel matrix (slighly less intuitive to create than Toeplitz)
H = hankel(t,r=[2,3,4,1])
print(H)

[[1 2 3 4]
 [2 3 4 3]
 [3 4 3 4]
 [4 3 4 1]]


## 5.6 Matrix addition and subtraction

- matrix addition and subtraction are simply item-wise addition / subtraction
- must have same number of elements (columns & rows)
- addition/subtraction is commutative (may seem trivial but it's important to remember because matrix multiplication is NOT commutative)

In [19]:
# Matrix addition
A = np.array([[0,5],[-4,6],[-3,0]])
B = np.array([[0,1],[1,1],[1,0]])
print(A + B)

[[ 0  6]
 [-3  7]
 [-2  0]]


## 5.7 Scalar-matrix multiplication

- matrix multiplication is involved enough to have its own chapter (later), but scalar multiplication is simple
- For scalar multiplication, just multiply the scalar value by each value of the matrix

## 5.8 "Shifting" a matrix

- "Shifting" a matrix means to add to the matrix a multiple of the identity matrix
- shifting is applied only to square matrices.
- The new, shifted matrix is often denoted as $\~A$

In [20]:
# Example of shifting a matrix
A = np.array([[1,3,0],[1,3,0],[2,2,7]])
I = np.eye(3)
shift = 0.1 * I
print (A + shift)

[[1.1 3.  0. ]
 [1.  3.1 0. ]
 [2.  2.  7.1]]


3 properties of matrix shifting:
1. only diagonal elements are affected
2. it can make identical rows distince (e.g. row 1 and 2 in above example)
3. when the $\lambda$ (scalar) is closer to zero, then $\~A$ is very similar to $A$.  (*I imagine this can be useful if you want to differentiate rows, but keep the matrix relatively the same.*)

- Shifting a matrix has important applications in statistics, machine learning, deep learning, etc
  - e.g. "regularization"

## 5.9 Diagonal and trace

### Diagonal

- the diagonal elements of a matrix can be extracted and converted into a vector
  - this is useful in statistics: the diagonal elements of a covariance matrix contain the variance of each variable
- matrix can be either square or rectangular

### Trace

- Trace produces a single number from a square matrix
- **IMPORTANT:** trace is only defined for square matrices
- it is indicated as $tr(A)$ and is defined as the sum of all diagonal elements of a matrix
- the trace operation has 2 applications in machine learning:
  - to compute the Frobenius norm of a matrix (measure of the magnitude of a matrix)
  - to measure the "distance" between 2 matrices

#### Code

In [21]:
# Trace
A = np.random.randn(4,4)
tr = np.trace(A)
print(tr)

-1.757961101733823


## 5.10 - 5.11 Exercises

### [PDF of Ch 05 exercises (done by hand)](exercises/Ch05-Matrices-Exercises.pdf)

## 5.12 Coding Challenges

1. Goal: Create a matrix that contains the dot products between all pairs of columns in the two other matrices.

- create two 4x2 matrices
- write a double for loop to compute the dot products between each column of both matrices
- the *i,j* element of the resulting matrix will be the dot product between column *i* of the first matrix and column *j* of the second matrix

In [22]:
A = np.random.randn(4, 2)
print(A)

[[-0.59596934 -0.55176662]
 [-0.00283465 -1.37527135]
 [-0.23863094 -1.14469584]
 [ 1.17711622 -1.50645791]]


In [23]:
B = np.random.randn(4, 2)
print(B)

[[-1.45405409  0.61831051]
 [-0.19320006  0.01560328]
 [-0.22320946 -0.83989436]
 [-1.69608932  1.38568091]]


In [24]:
# test - extract a column from B
print( B[:,0] )

[-1.45405409 -0.19320006 -0.22320946 -1.69608932]


In [25]:
dot_prods = []  # initialize empty array to hold 4 dot products

for i in range(0,2):  # from 0 up to but not including 2
  for j in range(0,2):
    col_A = A[:, i]
    col_B = B[:, j]
    dot = np.dot(col_A, col_B)
    dot_prods.append(dot)

print(dot_prods)

[-1.0761102482588993, 1.4629939191516033, 3.8785951350875543, -1.4886682252762173]


2. Create a symmetric matrix by starting with a dense random numbers matrix and applying 3 matrix operations: convert to triangular, transpose, matrix addition.

In [26]:
A = np.random.randn(6, 6)   # create random number matrix
print(A)

[[-4.82249263e-01 -3.85759847e-01  5.25134704e-01 -2.33371489e-01
   6.79686324e-01  1.55996942e+00]
 [-4.42901715e-01  6.78444133e-02 -2.00333457e-01  1.52552088e+00
  -6.72700859e-01 -3.70269423e-01]
 [-1.21934179e+00  1.53690786e+00  4.87684213e-01  5.07052560e-01
  -8.56643481e-02  5.93600790e-01]
 [ 2.56306846e+00  1.38690864e-01  1.10613246e-01  9.05109558e-01
  -3.91131630e-01  8.52616518e-01]
 [ 5.24637001e-01  1.64816337e+00  1.25403225e-03  1.31224509e-01
   4.78085632e-02 -1.96518046e-02]
 [-4.89119291e-01  1.47452540e+00 -1.32323801e+00 -9.76237784e-01
   4.19645494e-03 -8.87240403e-01]]


In [27]:
# 2a) convert to triangular
tri_A = np.tril(A)
print(tri_A)

[[-4.82249263e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-4.42901715e-01  6.78444133e-02  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [-1.21934179e+00  1.53690786e+00  4.87684213e-01  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 2.56306846e+00  1.38690864e-01  1.10613246e-01  9.05109558e-01
   0.00000000e+00  0.00000000e+00]
 [ 5.24637001e-01  1.64816337e+00  1.25403225e-03  1.31224509e-01
   4.78085632e-02  0.00000000e+00]
 [-4.89119291e-01  1.47452540e+00 -1.32323801e+00 -9.76237784e-01
   4.19645494e-03 -8.87240403e-01]]


In [28]:
# 2b) transpose
A_t = tri_A.T
print(A_t)

[[-4.82249263e-01 -4.42901715e-01 -1.21934179e+00  2.56306846e+00
   5.24637001e-01 -4.89119291e-01]
 [ 0.00000000e+00  6.78444133e-02  1.53690786e+00  1.38690864e-01
   1.64816337e+00  1.47452540e+00]
 [ 0.00000000e+00  0.00000000e+00  4.87684213e-01  1.10613246e-01
   1.25403225e-03 -1.32323801e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  9.05109558e-01
   1.31224509e-01 -9.76237784e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   4.78085632e-02  4.19645494e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -8.87240403e-01]]


In [29]:
# 2c) combine with addition
A_symm = tri_A + A_t
print(A_symm)

[[-9.64498527e-01 -4.42901715e-01 -1.21934179e+00  2.56306846e+00
   5.24637001e-01 -4.89119291e-01]
 [-4.42901715e-01  1.35688827e-01  1.53690786e+00  1.38690864e-01
   1.64816337e+00  1.47452540e+00]
 [-1.21934179e+00  1.53690786e+00  9.75368425e-01  1.10613246e-01
   1.25403225e-03 -1.32323801e+00]
 [ 2.56306846e+00  1.38690864e-01  1.10613246e-01  1.81021912e+00
   1.31224509e-01 -9.76237784e-01]
 [ 5.24637001e-01  1.64816337e+00  1.25403225e-03  1.31224509e-01
   9.56171265e-02  4.19645494e-03]
 [-4.89119291e-01  1.47452540e+00 -1.32323801e+00 -9.76237784e-01
   4.19645494e-03 -1.77448081e+00]]


3. Create a diagonal matrix of size 4x8 without using the diag() function. The diagonal elements should be 1,2,3,4. How much of your code would you need to change to create an 8x4 diagonal matrix?

In [30]:
A = np.array([1,2,3,4])
I = np.eye(4)
D = A * I
print(D)

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [31]:
# one way to change to 8x4 diagonal matrix is by concatenating the rows from a 4x4 zeroes matrix using np.concatenate
Z = np.zeros((4,4))
A2 = np.concatenate((D, Z), axis=0)
print(A2)

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
